import React from "react";
import { Link } from "react-router-dom";
import { Navbar } from "./Navbar";
import { Footer } from "./Footer";
import { Calendar, Leaf, Recycle, TreePine, ArrowLeft } from "lucide-react";

export function BlogPage() {
  return (
    <>
      <Navbar />

      {/* Back Link */}
      <div className="pt-24 sm:pt-28 bg-white">
        <div className="max-w-6xl mx-auto px-6">
          <Link
            to="/#blog"
            className="inline-flex items-center gap-2 text-sm font-medium text-[#23376D] transition-colors hover:text-[#4A7C6F]"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Journal
          </Link>
        </div>
      </div>

      {/* Hero Section */}
      <section className="pt-8 pb-20 bg-gradient-to-br from-green-50 to-white">
        <div className="max-w-6xl mx-auto px-6 text-center">
          <span className="inline-block px-4 py-2 rounded-full bg-green-100 text-green-700 font-medium mb-4">
            World Environment Day 2026
          </span>

          <h1 className="text-5xl font-bold text-gray-900 leading-tight">
            Circular Economy as Climate Action
          </h1>

          <div className="flex items-center justify-center gap-2 mt-6 text-gray-600">
            <Calendar size={18} />
            <span>June 5, 2026</span>
          </div>

          <p className="max-w-3xl mx-auto mt-8 text-lg text-gray-600">
            Celebrating how collaboration across the textile value chain
            transforms waste into valuable resources while reducing
            environmental impact.
          </p>
        </div>
      </section>

      {/* Featured Image */}
      <section className="py-10">
        <div className="max-w-6xl mx-auto px-6">
          <img
            src="/images/world-environment-day.jpg"
            alt="World Environment Day"
            className="w-full rounded-3xl shadow-2xl"
          />
        </div>
      </section>

      {/* Blog Content */}
      <section className="pb-24">
        <div className="max-w-4xl mx-auto px-6">
          <article className="prose prose-lg max-w-none">

            <p>
              On World Environment Day, the Wire Waste team joined hands
              with SSQ International and Jothi Papers to celebrate the
              theme <strong>"Circular Economy as Climate Action."</strong>
            </p>

            <h2>Turning Textile Waste into Sustainable Products</h2>

            <p>
              The journey begins with textile waste generated by brands
              and manufacturers. Through the Wire Waste ecosystem,
              materials flow through multiple stages before becoming
              useful products again.
            </p>

            <p>
              Jothi Papers converts textile waste into cotton sheets,
              creating tree-free paper from materials that would
              otherwise be discarded.
            </p>

            <p>
              SSQ International then uses these cotton sheets to create
              upcycled products using plant-based inks, ensuring
              sustainability throughout the production process.
            </p>

            <div className="bg-green-50 border-l-4 border-green-600 p-6 rounded-xl my-10">
              <p className="font-medium">
                Representatives from Wire Waste and SSQ International
                showcasing sustainable paper bags made from recovered
                textile waste.
              </p>
            </div>

            <h2>Circular Economy as Climate Action</h2>

            <ul>
              <li>Divert waste from landfills.</li>
              <li>Reduce greenhouse gas emissions.</li>
              <li>Extend material life cycles.</li>
              <li>Reduce virgin resource consumption.</li>
              <li>Promote sustainable production.</li>
            </ul>

            <h2>Celebrating World Environment Day</h2>

            <p>
              Teams came together for tree plantation activities,
              reinforcing a shared commitment to a greener future.
            </p>

            <p>
              Conference sessions explored textile circularity,
              responsible resource management, and sustainable business
              models.
            </p>

            <h2>Moving Forward Together</h2>

            <p>
              Sustainability requires collective action. Through
              collaboration, we can reduce waste, lower emissions, and
              create meaningful environmental impact.
            </p>

            <blockquote className="border-l-4 border-green-600 pl-6 italic text-xl font-medium">
              Happy World Environment Day from the Wire Waste Team! 🌱♻️
            </blockquote>

          </article>
        </div>
      </section>

      <Footer />
    </>
  );
}